#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtcanvas3d
Version  : 5.10.0
Release  : 1
URL      : http://download.qt.io/official_releases/qt/5.10/5.10.0/submodules/qtcanvas3d-everywhere-src-5.10.0.tar.xz
Source0  : http://download.qt.io/official_releases/qt/5.10/5.10.0/submodules/qtcanvas3d-everywhere-src-5.10.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qtcanvas3d-lib
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5OpenGLExtensions)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : qtbase-dev

%description
3D Models and textures used in the example courtesy of http://nobiax.deviantart.com/

%package lib
Summary: lib components for the qtcanvas3d package.
Group: Libraries

%description lib
lib components for the qtcanvas3d package.


%prep
%setup -q -n qtcanvas3d-everywhere-src-5.10.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
`pkg-config --variable=host_bins Qt5Core $(sed -n '/MODULE_VERSION */s///p' .qmake.conf 2>/dev/null)`/qmake --
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
make INSTALL_ROOT=%{buildroot} install

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/qml/QtCanvas3D/libqtcanvas3d.so
/usr/lib64/qt5/qml/QtCanvas3D/plugins.qmltypes
/usr/lib64/qt5/qml/QtCanvas3D/qmldir
